server:
  port: 8080
spring:
  application:
    name: RickandMorty
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:

  datasource:
    url: jdbc:postgresql://localhost:5432/rickandmorty
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

appDescription: "RickAndMorty API"
appVersion: "1.0.0"

adapter:
  restconsumer:
    url: "http://localhost:8080"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  default-group-name: my-api