version: '3.8'

services:
  app:
    build:
      context: ./config
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rickandmorty
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  db:
    image: postgres:13
    container_name: postgresqlv13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rickandmorty
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin